M48
; DRILL file {KiCad 9.0.1} date 2026-03-30T06:27:25-1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-30T06:27:25-10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X180.442Y-114.284
T2
X144.242Y-114.284
M30
